spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/planup?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: test1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  # Redis
  data:
    redis:
      host: localhost
      port: 6379
      # password:

  # 소셜
  security:
    oauth2:
      client:
        registration:
          # 1. 카카오 설정
          kakao:
            client-id: eb267eb7940fe0d84694af2f2254fe3d
            client-secret: UnLOEl5hCL6Gc2hMTwRmQaaXERUXH7WQ
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email

          # 2. 네이버 설정
          naver:
            client-id: EinflELU2WUWcp7dTNFW
            client-secret: elL9uWi132
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            client-name: Naver
            scope:
              - name
              - email

        # 3. Provider 설정 (네이버는 카카오와 달리 수동 설정 필요)
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 카카오는 'id'라는 필드가 고유 식별자

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 네이버는 'response' 안에 정보가 있음

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa